language: node_js
node_js:
- '4'
- 'node'
sudo: false
services:
- docker
- mongodb
script:
- npm run bootstrap
- npm run lint
- npm test
cache:
  directories:
    - node_modules
    - demo/server/node_modules
    - cloud/datasync/node_modules
